---
title: "TMA box plot"
author: "Jenn Ji"
date: "May 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggthemes)
library(dunn.test)
library(psych)
library(reshape2)
library(gridExtra)
library(cowplot)
library(pheatmap)
```

```{r}
ASS_dat <- read.csv("../../Data/A-S_data/17-001_10-008_11_010_ASS1_update_R.csv", header=TRUE, stringsAsFactors = FALSE)
other_dat <- read.csv("../../Data/A-S_data/17-001_11-010_ER_CTH_Napsin_HNF_update_R.csv", header=TRUE, stringsAsFactors = FALSE)
```

```{r}
# eliminate duplicates by VS number
ASS_dat_dedup <- ASS_dat[!duplicated(ASS_dat$VS),]

#exclude cases indicated by sheet
ASS_dat_clean <- ASS_dat_dedup[!(ASS_dat_dedup$Inclusion == "exclude"),]


keep = c("ASS1","VS","Dx.code","ASS.c1","ASS.c2","ASS1")
ass_table = ASS_dat_clean[keep]

order <- c("CCC","EC","SC","EC (CC change)","mixed SC/CCC", "AS", "Hyperplasia_w_CC","mixed EC/CCC","Mixed EC/SC","mixed")
ass_table$Dx.code <- factor(ass_table$Dx.code, levels = order)

```

```{r}
exclude_dx <- c("Mixed EC/SC","Hyperplasia_w_CC","mixed EC/CCC","mixed SC/CCC","mixed")
ass_table <- ass_table[-which(ass_table$Dx.code %in% exclude_dx),]

write.table(ass_table,"asstable.txt")
```

```{r}
#summarize the data
summary_table <- ass_table %>% 
  group_by(Dx.code) %>% 
  summarize(count = n())

#median_summary <- describeBy(x= ass_table, group = "Dx.code", mat = TRUE)
```


```{r}
p = ass_table %>%
  ggplot(aes(Dx.code,ASS1,color=Dx.code))+
  geom_boxplot(outlier.shape=NA, width = 0.5, boxlwd = 5)+geom_jitter(size = 1, width = 0.2, alpha = 0.8)+ 
  theme_hc()

  
#axis tickmark labels0
p2= p + scale_x_discrete(labels=c("CCC"="CC (n=62)","EC" = "EC (n = 120)","EC (CC change)" = "EC with CC change (n = 5)","SC" = "SC (n = 14)", "AS" = "AS (n = 20)"))+
  theme(axis.text.x=element_text(angle = - 25, hjust = 0.15, vjust = 0.8)) +
  ggtitle("ASS1")+
  scale_color_manual(values = c("#ba4661",
"#56ae6c",
"#ae559b",
"#aaa23f",
"#6c67bf",
"#b85f36")) +
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = 8))+
  theme(axis.title.y = element_text(size = 9))+
  ylab("Histoscore")+
  scale_y_continuous(limit=c(0,350))

p2
```


```{r}
#statistic tests, kruskal willis and posthoc dunn's test
kruskal.test(ASS1 ~ Dx.code, data = ass_table)

 
dun_test <- dunn.test(ass_table$ASS1,ass_table$Dx.code, method = "hs",list = FALSE)

dunn_test <- dun_test$P.adjusted %>% as.data.frame()
dunn_test$comparison <- dun_test$comparisons 
```

other markers
```{r}
other_clean <- other_dat[!(other_dat$Inclusion == "exclude"),]
#other_clean$CTH <- as.numeric(other_clean$CTH)
#other_clean$HNF1B <- as.numeric(other_clean$HNF1B)
#other_clean$Napsin <- as.numeric(other_clean$Napsin)
#other_clean$ER <- as.numeric(other_clean$ER)

keep2 = c("Dx.code","CTH","HNF1B","Napsin","ER")
other_table = other_clean[keep2]

other_melt <- reshape2::melt(other_table, id = "Dx.code")

# exclude N/As
other_melt <- other_melt[!(other_melt$value == "n/a"),]
other_melt$value <- as.numeric(other_melt$value)

```


```{r}
exclude_dx2 <- c("Mixed EC/SC","Hyperplasia_w_CC","polyp","mixed EC/CCC","mixed SC/CCC","CC_polyp")
other_melt <- other_melt[-which(other_melt$Dx.code %in% exclude_dx2),]
```

```{r}
summary_table2 <- other_melt %>% 
  group_by(Dx.code,variable) %>% 
  summarize(count = n())

#median_summary2 <- describeBy(x= other_melt, group = c("Dx.code","variable"), mat = TRUE)
```

```{r}
order <- c("CCC","EC","SC","EC (CC change)", "AS")
other_melt$Dx.code <- factor(other_melt$Dx.code, levels = order)


CTH <- subset(other_melt, variable == "CTH")
Napsin <- subset(other_melt, variable == "Napsin")
ER <- subset(other_melt, variable == "ER")
HNF1B <- subset (other_melt, variable =="HNF1B")
```

```{r}
p_cth = CTH %>%
  ggplot(aes(Dx.code,value,color=Dx.code))+
  geom_boxplot(outlier.shape=NA, width = 0.5, boxlwd = 5)+geom_jitter(size = 1, width = 0.2, alpha = 0.8)+ 
  theme_hc()
  
#axis tickmark labels0
p3= p_cth + scale_x_discrete(labels=c("CCC"="CC (n=52)","EC" = "EC (n = 124)","EC (CC change)" = "EC with CC change (n = 5)","SC" = "SC (n = 16)", "AS" = "AS (n = 11)"))+
  theme(axis.text.x=element_text(angle = - 25, hjust = 0.15, vjust = 0.8))  +
  ggtitle("CTH")+
  scale_color_manual(values = c("#ba4661",
"#56ae6c",
"#ae559b",
"#aaa23f",
"#6c67bf",
"#b85f36")) +
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = 8))+
  theme(axis.title.y = element_text(size = 9))+
  ylab("Histoscore")+
  scale_y_continuous(limit=c(0,350))

p3
```

```{r}
p_er = ER %>%
  ggplot(aes(Dx.code,value,color=Dx.code))+
  geom_boxplot(outlier.shape=NA, width = 0.5, boxlwd = 5)+geom_jitter(size = 1, width = 0.2, alpha = 0.8)+ 
  theme_hc()
  
#axis tickmark labels0
p4= p_er + scale_x_discrete(labels=c("CCC"="CC (n=51)","EC" = "EC (n = 123)","EC (CC change)" = "EC with CC change (n = 5)","SC" = "SC (n = 16)","mixed SC/CCC" = "Mixed SC/CCC (n = 5)", "AS" = "AS (n = 7)"))+
 theme(axis.text.x=element_text(angle = - 25, hjust = 0.15, vjust = 0.8))  +
  ggtitle("ER")+
  scale_color_manual(values = c("#ba4661",
"#56ae6c",
"#ae559b",
"#aaa23f",
"#6c67bf",
"#b85f36")) +
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = 8))+
  theme(axis.title.y = element_text(size = 9))+
  ylab("Histoscore")+
  scale_y_continuous(limit=c(0,350))

p4
```

```{r}
p_nap = Napsin %>%
  ggplot(aes(Dx.code,value,color=Dx.code))+
  geom_boxplot(outlier.shape=NA, width = 0.5, boxlwd = 5)+geom_jitter(size = 1, width = 0.2, alpha = 0.8)+ 
  theme_hc()
  
#axis tickmark labels0
p5= p_nap + scale_x_discrete(labels=c("CCC"="CC (n=52)","EC" = "EC (n = 124)","EC (CC change)" = "EC with CC change (n = 5)","SC" = "SC (n = 16)","mixed SC/CCC" = "Mixed SC/CCC (n = 5)", "AS" = "AS (n = 9)"))+
  theme(axis.text.x=element_text(angle = - 25, hjust = 0.15, vjust = 0.8))  +
  ggtitle("Napsin")+
  scale_color_manual(values = c("#ba4661",
"#56ae6c",
"#ae559b",
"#aaa23f",
"#6c67bf",
"#b85f36")) +
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = 8))+
  theme(axis.title.y = element_text(size = 9)) +
  scale_y_continuous(limit=c(0,350))+
  ylab("Histoscore")

p5
```

```{r}
p_hnf = HNF1B %>%
  ggplot(aes(Dx.code,value,color=Dx.code))+
  geom_boxplot(outlier.shape=NA, width = 0.5, boxlwd = 5)+geom_jitter(size = 1, width = 0.2, alpha = 0.8)+ 
  theme_hc()
  
#axis tickmark labels0
p6= p_hnf + scale_x_discrete(labels=c("CCC"="CC (n=52)","EC" = "EC (n = 124)","EC (CC change)" = "EC with CC change (n = 5)","SC" = "SC (n = 16)", "AS" = "AS (n = 11)"))+
  theme(axis.text.x=element_text(angle = - 25, hjust = 0.15, vjust = 0.8))  +
  ggtitle("HNF1B")+
  scale_color_manual(values = c("#ba4661",
"#56ae6c",
"#ae559b",
"#aaa23f",
"#6c67bf",
"#b85f36")) +
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size = 9))+
  theme(axis.title.y = element_text(size = 9))+
  ylab("Histoscore")+
  scale_y_continuous(limit=c(0,350))

p6
```

```{r}
grids <- plot_grid(p2,p3,p4,p5,p6, ncol = 3)
grids

```

Dunn's test using bj multiple test comparison
```{R}
dun_test_cth <- dunn.test(CTH$value,CTH$Dx.code, method = "hs",list = FALSE)

dunn_test_cth <- dun_test_cth$P.adjusted %>% as.data.frame()
dunn_test_cth$comparison <- dun_test_cth$comparisons 
```

ER
```{r}
dunn.test(ER$value,ER$Dx.code, method = "hs",list = FALSE)
```
Napsin
```{r}
dunn.test(Napsin$value,Napsin$Dx.code, method = "hs",list = FALSE)
```

HNF1b
```{r}
dunn.test(HNF1B$value,HNF1B$Dx.code, method = "hs",list = FALSE)
```

```{r}
pdf("asplot2.pdf", width = 13, height = 8.5)
grids
dev.off()
```

plot heatmap
```{R}
#join data
join <- dplyr::full_join(ASS_dat_clean,other_clean, by = c("VS", "Inclusion","Dx","Dx.code" ))
keep_heatmap <- c("VS","Dx.code","ASS1","CTH","HNF1B","Napsin","ER")
join_heatmap <- join[keep_heatmap]
join_heatmap_na <- na.omit(join_heatmap)
join_plot <- na.omit(join_heatmap)

order <- c("CCC","EC","EC (CC change)","SC","mixed SC/CCC", "AS", "Hyperplasia_w_CC","mixed EC/CCC","Mixed EC/SC")
join_heatmap_na$Dx.code <- factor(join_heatmap_na$Dx.code, levels = order) 
join_heatmap_na <- join_heatmap_na[order(join_heatmap_na$Dx.code),]

exclude_dx2 <- c("Mixed EC/SC","Hyperplasia_w_CC","polyp","mixed EC/CCC")
join_heatmap_na <- join_heatmap_na[-which(join_heatmap_na$Dx.code %in% exclude_dx2),]

join_heatmap_na <- join_heatmap_na %>% 
  rownames_to_column()

#master file
keep_master <- c("VS","Dx.code")
master <- join_heatmap_na[keep_master]

join_heatmap_na <- join_heatmap_na[,-c(1,3)]
join_heatmap_na<- tibble::column_to_rownames(join_heatmap_na,var = "VS")
join_heatmap_na <- t(join_heatmap_na) %>% as.data.frame()

```

```{r}
heatmapfnx <- function(df,annotations){
  annotate = data.frame(
    Dx = annotations[,"Dx.code"])
  
  rownames(annotate) = annotations[["VS"]]
  
  pheatmap(df, annotation_col= annotate,
           cluster_rows = FALSE, #turn clustering off
           cluster_cols = FALSE,
           annotation_names_row = TRUE,
           annotation_names_col = TRUE,
           show_rownames = T,
           show_colnames = F,
           fontsize = 6 
          )
}

heatmap1 <- heatmapfnx(join_heatmap_na,master)
```

```{r}
pdf("heatmap.pdf", width = 13, height = 8.5)
heatmap1
dev.off()
```

Correlation plot
```{R}
ASS_CTH <- ggplot(join_plot, aes(x=ASS1, y = CTH)) + geom_point()+
  facet_wrap(~Dx.code)
```

```{R}
ASS_HNF1B <- ggplot(join_plot, aes(x=ASS1, y = HNF1B)) + geom_point()+
  facet_wrap(~Dx.code)
```

```{R}
CTH_HNF1B <- ggplot(join_plot, aes(x=CTH, y = HNF1B)) + geom_point()+
  facet_wrap(~Dx.code)
```

```{r}
pdf("ASS_CTH.pdf", width = 13, height = 8.5)
ASS_CTH
dev.off()

pdf("ASS_HNF1B.pdf", width = 13, height = 8.5)
ASS_HNF1B
dev.off()

pdf("CTH_HNF1b.pdf", width = 13, height = 8.5)
CTH_HNF1B
dev.off()
```

```{r}
write.table(join, "join.txt")
```